version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    # environment:
    #   - name=value
    # env_file:
    #   - ./.env
    